controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # List the controllers that the controller_manager should load and manage.
    # The '.*' after the controller name tells it to load all parameters under that namespace.
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # --- ADD THIS NEW CONTROLLER ---
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    # --- ADD THE NEW GRIPPER CONTROLLER DEFINITION ---
    gripper_controller:
      type: gripper_action_controller/GripperActionController

# Parameters for the Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    # The type is already defined above, so this is not strictly necessary
    # but it's good practice to keep it for clarity.
    type: joint_state_broadcaster/JointStateBroadcaster

# Parameters for the Joint Trajectory Controller
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_Revolute-1
      - link1_Revolute-3
      - link2_Revolute-4
      - link3_Revolute-5
      - link4_Revolute-6
      - link5_Revolute-7
    command_interfaces:
      - position
    state_interfaces:
      - position
    # Adding state_publish_rate for good measure
    state_publish_rate: 50

# --- ADD PARAMETERS FOR THE NEW CONTROLLER ---
# Parameters for the Forward Position Controller (for interactive markers)
forward_position_controller:
  ros__parameters:
    joints:
      - base_link_Revolute-1
      - link1_Revolute-3
      - link2_Revolute-4
      - link3_Revolute-5
      - link4_Revolute-6
      - link5_Revolute-7
      - link6_Slider-8
    interface_name: position

# --- ADD PARAMETERS FOR THE NEW GRIPPER CONTROLLER ---
gripper_controller:
  ros__parameters:
    joint: link6_Slider-8
